server:
  port: 8080

spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://db:5432/saladdb}
    username: ${SPRING_DATASOURCE_USERNAME:saladuser}
    password: ${SPRING_DATASOURCE_PASSWORD:saladpass}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  flyway:
    enabled: false
    locations: classpath:db/migration

file:
  storage:
    path: ${FILE_STORAGE_PATH:/tmp/storage}

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql: TRACE
